### ISSUE TITLE
Public method for translating linq expression to odata string?

### ISSUE THREAD

**Issue by rekosko** [tocsoft/Linq2OData#4]
Hi there,

In original source code I was able to do something like:
```
var converter = new ODataExpressionConverter();
Expression<Func<T, bool>> exp = x => true;
var odataString = converter.Convert<T>(exp);
```
to get the odata string. Does this fork allows to do something similar?

**Comment by tocsoft** [comment]
we didn't but I've just pushed out a v0.6 release that adds the `AsODataQueryStringArguments()` extension.

You can now do this
```c#
 var args = Enumerable.Empty<Models.TestObject>()
                .AsQueryable()
                .Where(x => x.stringProperty == "string")
                .AsODataQueryStringArguments();
```
where we return an `IEnumerable<KeyValuePair<string, string>>` which is the set of query string parameters and values. _(Url encoding etc is a job that's left up to the reader.)_
